config/routes.rb
Rails.application.routes.draw do
  resources :tipo_mineracaos
  get 'welcome/index'
  resources :moedas
  # get '/moedas', to: 'moedas#index'
  # get '/inicio', to: 'welcome#index'
  root to: 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moeda.rb
class Moeda < ApplicationRecord
  belongs_to :tipo_mineracao, optional: true
end

app/models/tipo_mineracao.rb
class TipoMineracao < ApplicationRecord
  has_many :moedas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moedas_controller.rb
class MoedasController < ApplicationController
  # layout "nome_do_layout"
  before_action :set_moeda, only: %i[ show edit update destroy ]
  before_action :set_tipo_mineracao_opcoes, only: %i[new create edit update]

  # GET /moedas or /moedas.json
  def index
    @moedas = Moeda.all
  end

  # GET /moedas/1 or /moedas/1.json
  def show
  end

  # GET /moedas/new
  def new
    @moeda = Moeda.new
  end

  # GET /moedas/1/edit
  def edit
  end

  # POST /moedas or /moedas.json
  def create
    @moeda = Moeda.new(moeda_params)

    respond_to do |format|
      if @moeda.save
        format.html { redirect_to @moeda, notice: "Moeda was successfully created." }
        format.json { render :show, status: :created, location: @moeda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @moeda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moedas/1 or /moedas/1.json
  def update
    respond_to do |format|
      if @moeda.update(moeda_params)
        format.html { redirect_to @moeda, notice: "Moeda was successfully updated." }
        format.json { render :show, status: :ok, location: @moeda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @moeda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moedas/1 or /moedas/1.json
  def destroy
    @moeda.destroy
    respond_to do |format|
      format.html { redirect_to moedas_url, notice: "Moeda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_tipo_mineracao_opcoes
    @tipo_mineracao_opcoes = TipoMineracao.all.pluck(:descricao, :id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_moeda
    @moeda = Moeda.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def moeda_params
    params.require(:moeda).permit(:descricao, :sigla, :url_imagem, :tipo_mineracao_id)
  end
end

app/controllers/tipo_mineracaos_controller.rb
class TipoMineracaosController < ApplicationController
  before_action :set_tipo_mineracao, only: %i[ show edit update destroy ]

  # GET /tipo_mineracaos or /tipo_mineracaos.json
  def index
    @tipo_mineracaos = TipoMineracao.all
  end

  # GET /tipo_mineracaos/1 or /tipo_mineracaos/1.json
  def show
  end

  # GET /tipo_mineracaos/new
  def new
    @tipo_mineracao = TipoMineracao.new
  end

  # GET /tipo_mineracaos/1/edit
  def edit
  end

  # POST /tipo_mineracaos or /tipo_mineracaos.json
  def create
    @tipo_mineracao = TipoMineracao.new(tipo_mineracao_params)

    respond_to do |format|
      if @tipo_mineracao.save
        format.html { redirect_to @tipo_mineracao, notice: "Tipo mineracao was successfully created." }
        format.json { render :show, status: :created, location: @tipo_mineracao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_mineracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_mineracaos/1 or /tipo_mineracaos/1.json
  def update
    respond_to do |format|
      if @tipo_mineracao.update(tipo_mineracao_params)
        format.html { redirect_to @tipo_mineracao, notice: "Tipo mineracao was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_mineracao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_mineracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_mineracaos/1 or /tipo_mineracaos/1.json
  def destroy
    @tipo_mineracao.destroy
    respond_to do |format|
      format.html { redirect_to tipo_mineracaos_url, notice: "Tipo mineracao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_mineracao
      @tipo_mineracao = TipoMineracao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_mineracao_params
      params.require(:tipo_mineracao).permit(:descricao, :sigla)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @meu_nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime('%d/%m/%Y')
  end

  def ambiente_rails
    if Rails.env.development?
      "Desenvolvimento"
    elsif Rails.env.production?
      "Produção"
    else
      "Teste"
    end
  end

  def local(locale)
    I18n.locale == :en ? 'Estados Unidos' : 'Português do Brasil'
  end
end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/tipo_mineracaos_helper.rb
module TipoMineracaosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CryptoWallet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>-->
  </body>
</html>

app/views/moedas/_form.html.erb
<%= form_with(model: moeda) do |form| %>
  <% if moeda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(moeda.errors.count, "error") %> prohibited this moeda from being saved:</h2>

      <ul>
        <% moeda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :sigla %>
    <%= form.text_field :sigla %>
  </div>

  <div class="field">
    <%= form.label :url_imagem %>
    <%= form.text_field :url_imagem %>
    <% if moeda.url_imagem? %>
      <%= image_tag moeda.url_imagem, width: 65 %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :tipo_mineracao_id %>
    <%= form.select('tipo_mineracao_id', @tipo_mineracao_opcoes, { include_blank: 'Selecione o tipo de mineração' }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moedas/edit.html.erb
<h1>Editing Moeda</h1>

<%= render 'form', moeda: @moeda %>

<%= link_to 'Visualizar', @moeda %> |
<%= link_to 'Voltar à Lista', moedas_path %>

app/views/moedas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moedas</h1>

<table>
  <thead>
  <tr>
    <th>Descrição</th>
    <th>Sigla</th>
    <th>Imagem</th>
    <th>Tipo de mineração</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @moedas.each do |moeda| %>
    <tr>
      <td><%= moeda.descricao %></td>
      <td><%= moeda.sigla %></td>
      <!--      <td><img src="<%#= moeda.url_imagem %>" style="width: 65px;"></td>-->
      <td><%= image_tag moeda.url_imagem, width: '50', height: 'auto' %></td>
      <td><%= moeda.tipo_mineracao.descricao %> (<%= moeda.tipo_mineracao.sigla %>)</td>
      <td><%= link_to 'Visualizar', moeda %></td>
      <td><%= link_to 'Editar', edit_moeda_path(moeda) %></td>
      <td><%= link_to 'Excluir', moeda, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastar', new_moeda_path %>
<%= link_to 'Voltar à Index', welcome_index_path %>

app/views/moedas/new.html.erb
<h1>New Moeda</h1>

<%= render 'form', moeda: @moeda %>

<%= link_to 'Back', moedas_path %>

app/views/moedas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @moeda.descricao %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @moeda.sigla %>
</p>

<p>
  <strong>Url imagem:</strong>
  <%= @moeda.url_imagem %>
</p>

<%= link_to 'Editar', edit_moeda_path(@moeda) %> |
<%= link_to 'Voltar à Lista', moedas_path %>

app/views/tipo_mineracaos/_form.html.erb
<%= form_with(model: tipo_mineracao) do |form| %>
  <% if tipo_mineracao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_mineracao.errors.count, "error") %> prohibited this tipo_mineracao from being saved:</h2>

      <ul>
        <% tipo_mineracao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :sigla %>
    <%= form.text_field :sigla %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipo_mineracaos/edit.html.erb
<h1>Editing Tipo Mineracao</h1>

<%= render 'form', tipo_mineracao: @tipo_mineracao %>

<%= link_to 'Show', @tipo_mineracao %> |
<%= link_to 'Back', tipo_mineracaos_path %>

app/views/tipo_mineracaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Mineracaos</h1>

<table>
  <thead>
  <tr>
    <th>Descricao</th>
    <th>Sigla</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tipo_mineracaos.each do |tipo_mineracao| %>
    <tr>
      <td><%= tipo_mineracao.descricao %></td>
      <td><%= tipo_mineracao.sigla %></td>
      <td><%= link_to 'Show', tipo_mineracao %></td>
      <td><%= link_to 'Edit', edit_tipo_mineracao_path(tipo_mineracao) %></td>
      <td><%= link_to 'Destroy', tipo_mineracao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Mineracao', new_tipo_mineracao_path %>
<%= link_to 'Voltar à Index', welcome_index_path %>

app/views/tipo_mineracaos/new.html.erb
<h1>New Tipo Mineracao</h1>

<%= render 'form', tipo_mineracao: @tipo_mineracao %>

<%= link_to 'Back', tipo_mineracaos_path %>

app/views/tipo_mineracaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_mineracao.descricao %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @tipo_mineracao.sigla %>
</p>

<%= link_to 'Edit', edit_tipo_mineracao_path(@tipo_mineracao) %> |
<%= link_to 'Back', tipo_mineracaos_path %>

app/views/welcome/_menu.html.erb
<ul>
  <li>
    <%= link_to 'Moedas', moedas_path %>
  </li>
  <li>
    <%= link_to 'Tipos de Mineração', tipo_mineracaos_path %>
  </li>
</ul>

app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo,
  <strong><%= @meu_nome %></strong>
  ao Crypto Wallet App!</h1>
<!--<p><strong>Data:</strong> <%#= data_br(Date.today) %></p>-->
<p><strong>Data:</strong> <%= Date.today %></p>
<%= render 'menu' %>
<p>Você está no ambiente de:
  <strong>
    <%= ambiente_rails %>
  </strong>
</p>
<p>O idioma usado nessa aplicação é: <strong><%= local(I18n.locale) %></strong></p>